plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs48.github.io # the base hostname & protocol for your site
baseurl: "/"  # the subpath of your site, e.g. "/blog"

course: "CS48"

kramdown:
   parse_block_html: false

title: "UCSB CS48"
github_url: https://github.com/ucsb-cs48/ucsb-cs48.github.io

on_campus: http://proquest.safaribooksonline.com
off_campus: http://proquest.safaribooksonline.com.proxy.library.ucsb.edu:2048/

hfj_url: book/programming/java/0596009208
hfdp_url: book/software-engineering-and-development/patterns/0596007124 

exclude:
  - 'vendor'
  - 'setup.sh'
  - 'jekyll.sh'

timezone: America/Los_Angeles

collections:
  topics:
    output: true
    permalink: /topics/:path/

  pytopics:
    output: true
    permalink: /pytopics/:path/

  javatopics:
    output: true
    permalink: /javatopics/:path/
    
  jstopics:
    output: true
    permalink: /jstopics/:path/   

  standards:
    output: true
    permalink: /standards/:path/

  patterns:
    output: true
    permalink: /patterns/:path/

  tutorials:
    output: true
    permalink: /tutorials/:path/

  textbooks:
    output: true
    permalink: /textbooks/:path/

  hfj:
    output: true
    permalink: /hfj/:path/

  hfdp:
    output: true
    permalink: /hfdp/:path/
    
  resources:
    output: true
    permalink: /resources/:path/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      layout: "default"

  - scope:
      path: ""
      type: topics
    values:
      layout: default
      
  - scope:
      path: ""
      type: pytopics
    values:
      layout: default      

  - scope:
      path: ""
      type: javatopics
    values:
      layout: default      

  - scope:
      path: ""
      type: jstopics
    values:
      layout: default      


  - scope:
      path: ""
      type: standards
    values:
      layout: standard

  - scope:
      path: ""
      type: patterns
    values:
      layout: pattern

  - scope:
      path: ""
      type: tutorials
    values:
      layout: tutorial
      
  - scope:
      path: ""
      type: resources
    values:
      layout: default

include:
  - _pages


  
